apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      containers:
      - name: login-service
        image: fpzkryddan/buildsomethingproject-login_service:latest
        ports:
        - containerPort: 5001
        env:
        - name: DATABASE_SERVICE_URL
          value: "http://database-service:5002"
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  selector:
    app: login-service
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
