apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
      - name: task-service
        image: fpzkryddan/buildsomethingproject-task_service:latest
        ports:
        - containerPort: 5003
        env:
        - name: DATABASE_SERVICE_URL
          value: "http://database-service:5002"
---
apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  selector:
    app: task-service
  ports:
  - protocol: TCP
    port: 5003
    targetPort: 5003
